### ISSUE TITLE
Bluetooth: hci0: do not support firmware rome 0x1020200

### ISSUE THREAD

**Issue by williampaulo** [jeremyb31/bluetooth-4.13-ath3004-rome#1]
Hello, I'm using Debian 9 and I upgraded the kernel to 4.13. I'm having problems with my bluetooth ar3012.
looking in forums, I found https://askubuntu.com/a/1002502/686430 and did all the camandos, however that is now appearing the following log:

`Bluetooth: hci0: do not support firmware rome 0x1020200`

Can you help me?

**Comment by jeremyb31** [comment]
Post results from terminal for lspci -nnk | grep -iA3 net; lsusb
This source is for just a few of these bluetooth devices

**Comment by williampaulo** [comment]
lspci -nnk | grep -iA3 net; lsusb
01:00.0 Network controller [0280]: Qualcomm Atheros AR9485 Wireless Network Adapter [168c:0032] (rev 01)
	Subsystem: Samsung Electronics Co Ltd AR9485 Wireless Network Adapter [144d:4105]
	Kernel driver in use: ath9k
	Kernel modules: ath9k
02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller [10ec:8136] (rev 05)
	Subsystem: Samsung Electronics Co Ltd RTL8101/2/6E PCI Express Fast Ethernet controller [144d:c708]
	Kernel driver in use: r8169
	Kernel modules: r8169
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 2232:1041 Silicon Motion 
Bus 001 Device 003: ID 0cf3:3004 Atheros Communications, Inc. AR3012 Bluetooth 4.0
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by jeremyb31** [comment]
Undo what you did as this source code will not help that version.  Using Debian you might need firmware-atheros from nonfree or restricted repos

**Comment by williampaulo** [comment]
Okay, did I know how to undo?
just run the command 'dkms remove bluetooth-3004 / 0.1' ?

**Comment by jeremyb31** [comment]
sudo dkms remove bluetooth-3004/0.1 --all
Might do it, then see if anything named bluetooth-3004 is in /usr/src/ or /var/lib/dkms
The biggest issue with your bluetooth was fixed in the 3.16 kernel if I remember correctly as there was an issue with initiating something with the USB bus and the firmware upload and they only worked maybe once in 5 boots

**Comment by williampaulo** [comment]
Ok, all right. Thank you for your help.
